# Generated by Django 5.2 on 2025-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_productimage_image_productimage_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='pimage',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
