# Generated by Django 5.2 on 2025-04-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_productimage_pimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productimage',
        ),
    ]
